version: '3'

networks:
  kafka_network:
    name: kafka_network
  kafka_final_network:
    name: kafka_final_network
    
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: capstone_drowsiness_zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka_network
      
  kafka:
    image: wurstmeister/kafka
    container_name: capstone_drowsiness_kafka_server
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "capstone_drowsiness_intake:5:1,capstone_drowsiness_output:1:1"
      #KAFKA_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      #KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
    networks:
      - kafka_network
    depends_on:
      - zookeeper
      