version: '3'

networks:
  kafka_network:
    name: kafka_network
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka_network
  kafka:
    image: wurstmeister/kafka
    container_name: kafka-server
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "testing321:5:1, results:1:1"
    networks:
      - kafka_network
    depends_on:
      - zookeeper